### ISSUE TITLE
Changing brightness also changes the temperature

### ISSUE THREAD

**Issue by jghaanstra** [athombv/com.lifx#5] opened 2016-10-16 20:05 UTC
**What is your Homey version (Settings → System)?**
firmware 0.10.5 / LIFX app 2.0.2

**What did you try to achieve?**
Change the brightness of a LIFX bulb from a flow.

_Please include detailed steps how we can reproduce the issue_
Create a flow with a action card to change the brightness of a LIFX bulb from 100% to 15%. Initially set the LIFX bulb from the LIFX smartphone app to a 3200K temperature.

**What was the result?**
The brightness is changed to 14% (although I set the action card to 15%) but also the temperature of the bulb has changed to 3345K while I only set changed the brightness through a flow.

**What did you expect as result?**
That only the brightness is changed. When I now set the brightness back to 100% from a flow my LIFX bulb has another temperature which is annoying.

**Any other remarks**
Of course you can work around this by also using the temperature action card to set the temperature back to it's initial temperature (set at 87% for 3200K) but that should not by necessary.

**Comment by RobinBol** [comment] 2016-12-07 11:34
This issue is caused by the fact that you use the mobile app to change the temperature. This isn't broadcasted to Homey so Homey will update the bulb with the temperature that it knows (3345K), and not which is set by the mobile app (3200K).

The fix for this issue is also the fix for issue #4, which is to listen to the information a bulb broadcasts when its state is being changed. For this I will create new issue, I am in contact with the developer on node-lifx to try to add this functionality.

**Comment by RobinBol** [comment] 2016-12-07 11:50
For now I will close this issue, to replace it with #6.

**Closed by RobinBol** 2016-12-07 11:50 UTC
